services:
  backend-server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    networks:
      - earthMates_network
    depends_on:
      earthMates_minio:
        condition: service_healthy

  earthMates_minio:
    container_name: earthMates-minio
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "mates"
      MINIO_ROOT_PASSWORD: "mates@1234"
    volumes:
      - minio_data:/data
    networks:
      - earthMates_network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server --console-address ":9001" /templates

volumes:
  minio_data:
networks:
  earthMates_network:
    driver: bridge
